@startuml

participant User as user
participant Hub as hub
database HubDB as db
queue "Service Bus" as que
participant Service as svc
participant "Document Manager" as dm
participant Frontify as fnt

user -> hub 
group Templates
hub -> svc ++ #gold: Get Templates
svc -> fnt ++ #gold: Get Templates
fnt --> svc --
svc -> fnt ++ #gold: Get Template Details
fnt --> svc --
svc --> hub --
end

hub -> hub ++ #gold: Prepare Text and Images

hub -> que  ++ #gold : Publish Brochure Artifacts 
hub --> user --:done

    que -> svc ++ #gold: Subscribe
loop
        svc -> fnt ++ #gold: Load artifacts
        fnt --> svc --
end
        svc -> fnt ++ #gold : Generate Brochure
        fnt --> svc -- : 
        svc -> dm ++ #gold: Store
        dm --> svc --: Saved
    svc -> que --: Publish
hub <- que --++ #gold: Subscribe Brochure Metadata
hub -> db : Add Brochure to attachments
hub --> user --: Notify

====

user -> hub ++ #gold
hub -> dm ++ #gold: Access Brochure
dm --> hub --: 
hub --> user

@enduml
