@startuml
!include <C4/C4_Container>

LAYOUT_WITH_LEGEND()
LAYOUT_LEFT_RIGHT()
AddElementTag("microService", $shape=EightSidedShape(), $fontColor="white", $legendText="micro service\neight sided")
AddElementTag("storage", $shape=RoundedBoxShape(), $fontColor="white")

SHOW_PERSON_OUTLINE()
Person( user, User, "A User")
System(ns, "Knight Frank System") 
System(app, "Brochure Service", "Allows users to create brochures", $tags = "microService")  
SystemDb(cosmos, "CosmosDB", "Content Managemnt Storage", $tags = "storage")
System_Ext(frontify, "Frontify", "External Brochure generation service")

Rel(user, ns, "Selects activity for brochure generation", "Https")
Rel(ns, app, " Uses the brochure service", "Https")
Rel(app, frontify, "Generate Brochure", "Https")
Rel(app, cosmos, "Cache usage detail ")

@enduml