@startuml System
!include <C4/C4_Component>
!include <azure/AzureCommon>
!include <azure/Compute/AzureFunction>
!include <azure/Web/AzureAPIManagement>
!include <azure/Integration/AzureServiceBusTopic>

LAYOUT_LEFT_RIGHT()

AddElementTag("microService", $shape=EightSidedShape(), $fontColor="white", $legendText="micro service\neight sided")
AddElementTag("storage", $shape=RoundedBoxShape(), $fontColor="white")


AzureAPIManagement(apim, "APIM", "Management")
AzureServiceBusTopic(sbus, "Serice Bus Topic", "Integration")
Container_Boundary(app, "Address Service", "Allows users to read address information", $tags = "microService") {
    AzureFunction(aFunc, "Function", "Http/Sbus Trigger")
    Component(compDom, "Domain Logic Component", "Process, Rules and validation")
    Component(compSec, "Security Component", "Provides functionality to validate callers and grant access to the service ")

}
Rel(apim, aFunc, "HTTP Trigger") 
Rel(sbus, aFunc, "Service Bus Trigger")

Rel(aFunc, compDom, "")
Rel(aFunc, compSec, "")

@enduml
