@startuml DeploymentView
!include <C4/C4_Component>
!include <azure/AzureCommon>
!include <azure/Compute/AzureFunction>
!include <azure/Web/AzureAPIManagement>
!include <azure/Integration/AzureServiceBusTopic>
!include <azure/Networking/AzureApplicationGateway>
!include <azure/Networking/All>
!include <azure/Web/AzureWebApp>
!include <azure/DevOps/AzureApplicationInsights>
!include <azure/Storage/AzureBlobStorage>
!include <azure/Databases/AzureCosmosDb>
!include <azure/Security/AzureKeyVault>
!include <azure/Identity/AzureAppRegistration>
!include <azure/Identity/AzureActiveDirectory>
!include <azure/Identity/AzureManagedIdentity>

'LAYOUT_WITH_LEGEND()
'LAYOUT_LEFT_RIGHT()

AddElementTag("microService", $shape=EightSidedShape(), $fontColor="white", $legendText="micro service\neight sided")
AddElementTag("storage", $shape=RoundedBoxShape(), $fontColor="white")

System_Boundary(s1, "Knight Frank") {

    AzureWebApp(local, "Application", "Internal")
    AzureActiveDirectory(ad, "", "Active Directory")
    AzureManagedIdentity(miapp, "Managed Identity", "route")

    Container_Boundary(c1, "Shared Subscription") {

        Container_Boundary(rgsh, "rg-shared-env-ne") {
            AzureAPIManagement(apimI, "apim-shared-env-ne", "Internal Interface")
            apimI -up-> ad : Validate App Registration
        }

        AzureManagedIdentity(misvc, "Managed Identity", "route")
        AzureAppRegistration(reg, "", "Application Registration")

    }
    
    Container_Boundary(c2, "Hub Subscription") {
        Container_Boundary(rggw, "rg-hub-frontify-env-ne") {
            AzureFunction(svc, "func-frontify-env-ne", "Azure Function")
            AzureApplicationInsights(ai, "appi-frontify", "Application Insights")
            AzureBlobStorage(st, "stFrontifyEnvNe", "Atorage Account")
            AzureKeyVault(key, "key-frontify-env-ne", "Key Vault")

            svc --> ai : uses
            svc --> st : uses
            svc --> key : uses
            svc -up-> reg : register
        }

        Container_Boundary(rgsd, "rg-hub-data-env-ne") {
            AzureCosmosDb(db, "cosmos-hub-data-env-ne", "Container - Frontify")
        }

        svc --> db : uses
        apimI -> svc 
        local ---> apimI

        apimI -down-> misvc : register
        svc -up-> misvc : validate
    }

    rgsh -[hidden]- rggw
    rgsh -[hidden]- rgsd

    local -down-> miapp : register
    apimI -up-> miapp : validate
    ad -down-> reg : validate

}

System_Ext(extFrontify, "Frontify", "External Brochure Generation service")
svc --> extFrontify

@enduml
